// Country data for the country selector and international phone input.
// `dial` = calling code (no +). `min`/`max` = expected national number length
// (digits after the dial code) used to bound the phone input per country.
export type Country = {
  name: string;
  iso2: string;
  dial: string;
  min: number;
  max: number;
};

const BASE_COUNTRIES: Country[] = [
  { name: "Afghanistan", iso2: "AF", dial: "93", min: 9, max: 9 },
  { name: "Albania", iso2: "AL", dial: "355", min: 8, max: 9 },
  { name: "Algeria", iso2: "DZ", dial: "213", min: 9, max: 9 },
  { name: "Argentina", iso2: "AR", dial: "54", min: 10, max: 11 },
  { name: "Armenia", iso2: "AM", dial: "374", min: 8, max: 8 },
  { name: "Australia", iso2: "AU", dial: "61", min: 9, max: 9 },
  { name: "Austria", iso2: "AT", dial: "43", min: 7, max: 13 },
  { name: "Azerbaijan", iso2: "AZ", dial: "994", min: 9, max: 9 },
  { name: "Bahrain", iso2: "BH", dial: "973", min: 8, max: 8 },
  { name: "Bangladesh", iso2: "BD", dial: "880", min: 10, max: 10 },
  { name: "Belarus", iso2: "BY", dial: "375", min: 9, max: 9 },
  { name: "Belgium", iso2: "BE", dial: "32", min: 8, max: 9 },
  { name: "Bolivia", iso2: "BO", dial: "591", min: 8, max: 8 },
  { name: "Bosnia and Herzegovina", iso2: "BA", dial: "387", min: 8, max: 8 },
  { name: "Brazil", iso2: "BR", dial: "55", min: 10, max: 11 },
  { name: "Bulgaria", iso2: "BG", dial: "359", min: 8, max: 9 },
  { name: "Cambodia", iso2: "KH", dial: "855", min: 8, max: 9 },
  { name: "Cameroon", iso2: "CM", dial: "237", min: 9, max: 9 },
  { name: "Canada", iso2: "CA", dial: "1", min: 10, max: 10 },
  { name: "Chile", iso2: "CL", dial: "56", min: 9, max: 9 },
  { name: "China", iso2: "CN", dial: "86", min: 11, max: 11 },
  { name: "Colombia", iso2: "CO", dial: "57", min: 10, max: 10 },
  { name: "Costa Rica", iso2: "CR", dial: "506", min: 8, max: 8 },
  { name: "Croatia", iso2: "HR", dial: "385", min: 8, max: 9 },
  { name: "Cyprus", iso2: "CY", dial: "357", min: 8, max: 8 },
  { name: "Czechia", iso2: "CZ", dial: "420", min: 9, max: 9 },
  { name: "Denmark", iso2: "DK", dial: "45", min: 8, max: 8 },
  { name: "Dominican Republic", iso2: "DO", dial: "1", min: 10, max: 10 },
  { name: "Ecuador", iso2: "EC", dial: "593", min: 9, max: 9 },
  { name: "Egypt", iso2: "EG", dial: "20", min: 10, max: 10 },
  { name: "El Salvador", iso2: "SV", dial: "503", min: 8, max: 8 },
  { name: "Estonia", iso2: "EE", dial: "372", min: 7, max: 8 },
  { name: "Ethiopia", iso2: "ET", dial: "251", min: 9, max: 9 },
  { name: "Finland", iso2: "FI", dial: "358", min: 9, max: 10 },
  { name: "France", iso2: "FR", dial: "33", min: 9, max: 9 },
  { name: "Georgia", iso2: "GE", dial: "995", min: 9, max: 9 },
  { name: "Germany", iso2: "DE", dial: "49", min: 10, max: 11 },
  { name: "Ghana", iso2: "GH", dial: "233", min: 9, max: 9 },
  { name: "Greece", iso2: "GR", dial: "30", min: 10, max: 10 },
  { name: "Guatemala", iso2: "GT", dial: "502", min: 8, max: 8 },
  { name: "Honduras", iso2: "HN", dial: "504", min: 8, max: 8 },
  { name: "Hong Kong", iso2: "HK", dial: "852", min: 8, max: 8 },
  { name: "Hungary", iso2: "HU", dial: "36", min: 9, max: 9 },
  { name: "Iceland", iso2: "IS", dial: "354", min: 7, max: 9 },
  { name: "India", iso2: "IN", dial: "91", min: 10, max: 10 },
  { name: "Indonesia", iso2: "ID", dial: "62", min: 9, max: 12 },
  { name: "Iraq", iso2: "IQ", dial: "964", min: 10, max: 10 },
  { name: "Ireland", iso2: "IE", dial: "353", min: 9, max: 9 },
  { name: "Israel", iso2: "IL", dial: "972", min: 9, max: 9 },
  { name: "Italy", iso2: "IT", dial: "39", min: 9, max: 11 },
  { name: "Jamaica", iso2: "JM", dial: "1", min: 10, max: 10 },
  { name: "Japan", iso2: "JP", dial: "81", min: 10, max: 10 },
  { name: "Jordan", iso2: "JO", dial: "962", min: 9, max: 9 },
  { name: "Kazakhstan", iso2: "KZ", dial: "7", min: 10, max: 10 },
  { name: "Kenya", iso2: "KE", dial: "254", min: 9, max: 9 },
  { name: "Kuwait", iso2: "KW", dial: "965", min: 8, max: 8 },
  { name: "Kyrgyzstan", iso2: "KG", dial: "996", min: 9, max: 9 },
  { name: "Latvia", iso2: "LV", dial: "371", min: 8, max: 8 },
  { name: "Lebanon", iso2: "LB", dial: "961", min: 7, max: 8 },
  { name: "Libya", iso2: "LY", dial: "218", min: 9, max: 9 },
  { name: "Lithuania", iso2: "LT", dial: "370", min: 8, max: 8 },
  { name: "Luxembourg", iso2: "LU", dial: "352", min: 8, max: 9 },
  { name: "Malaysia", iso2: "MY", dial: "60", min: 9, max: 10 },
  { name: "Maldives", iso2: "MV", dial: "960", min: 7, max: 7 },
  { name: "Malta", iso2: "MT", dial: "356", min: 8, max: 8 },
  { name: "Mauritius", iso2: "MU", dial: "230", min: 8, max: 8 },
  { name: "Mexico", iso2: "MX", dial: "52", min: 10, max: 10 },
  { name: "Moldova", iso2: "MD", dial: "373", min: 8, max: 8 },
  { name: "Morocco", iso2: "MA", dial: "212", min: 9, max: 9 },
  { name: "Nepal", iso2: "NP", dial: "977", min: 10, max: 10 },
  { name: "Netherlands", iso2: "NL", dial: "31", min: 9, max: 9 },
  { name: "New Zealand", iso2: "NZ", dial: "64", min: 8, max: 10 },
  { name: "Nigeria", iso2: "NG", dial: "234", min: 10, max: 10 },
  { name: "North Macedonia", iso2: "MK", dial: "389", min: 8, max: 8 },
  { name: "Norway", iso2: "NO", dial: "47", min: 8, max: 8 },
  { name: "Oman", iso2: "OM", dial: "968", min: 8, max: 8 },
  { name: "Pakistan", iso2: "PK", dial: "92", min: 10, max: 10 },
  { name: "Panama", iso2: "PA", dial: "507", min: 8, max: 8 },
  { name: "Paraguay", iso2: "PY", dial: "595", min: 9, max: 9 },
  { name: "Peru", iso2: "PE", dial: "51", min: 9, max: 9 },
  { name: "Philippines", iso2: "PH", dial: "63", min: 10, max: 10 },
  { name: "Poland", iso2: "PL", dial: "48", min: 9, max: 9 },
  { name: "Portugal", iso2: "PT", dial: "351", min: 9, max: 9 },
  { name: "Qatar", iso2: "QA", dial: "974", min: 8, max: 8 },
  { name: "Romania", iso2: "RO", dial: "40", min: 9, max: 9 },
  { name: "Russia", iso2: "RU", dial: "7", min: 10, max: 10 },
  { name: "Saudi Arabia", iso2: "SA", dial: "966", min: 9, max: 9 },
  { name: "Senegal", iso2: "SN", dial: "221", min: 9, max: 9 },
  { name: "Serbia", iso2: "RS", dial: "381", min: 8, max: 9 },
  { name: "Singapore", iso2: "SG", dial: "65", min: 8, max: 8 },
  { name: "Slovakia", iso2: "SK", dial: "421", min: 9, max: 9 },
  { name: "Slovenia", iso2: "SI", dial: "386", min: 8, max: 8 },
  { name: "South Africa", iso2: "ZA", dial: "27", min: 9, max: 9 },
  { name: "South Korea", iso2: "KR", dial: "82", min: 9, max: 10 },
  { name: "Spain", iso2: "ES", dial: "34", min: 9, max: 9 },
  { name: "Sri Lanka", iso2: "LK", dial: "94", min: 9, max: 9 },
  { name: "Sweden", iso2: "SE", dial: "46", min: 7, max: 9 },
  { name: "Switzerland", iso2: "CH", dial: "41", min: 9, max: 9 },
  { name: "Taiwan", iso2: "TW", dial: "886", min: 9, max: 9 },
  { name: "Tanzania", iso2: "TZ", dial: "255", min: 9, max: 9 },
  { name: "Thailand", iso2: "TH", dial: "66", min: 9, max: 9 },
  { name: "Tunisia", iso2: "TN", dial: "216", min: 8, max: 8 },
  { name: "Turkey", iso2: "TR", dial: "90", min: 10, max: 10 },
  { name: "Uganda", iso2: "UG", dial: "256", min: 9, max: 9 },
  { name: "Ukraine", iso2: "UA", dial: "380", min: 9, max: 9 },
  { name: "United Arab Emirates", iso2: "AE", dial: "971", min: 9, max: 9 },
  { name: "United Kingdom", iso2: "GB", dial: "44", min: 10, max: 10 },
  { name: "United States", iso2: "US", dial: "1", min: 10, max: 10 },
  { name: "Uruguay", iso2: "UY", dial: "598", min: 8, max: 8 },
  { name: "Uzbekistan", iso2: "UZ", dial: "998", min: 9, max: 9 },
  { name: "Venezuela", iso2: "VE", dial: "58", min: 10, max: 10 },
  { name: "Vietnam", iso2: "VN", dial: "84", min: 9, max: 10 },
  { name: "Yemen", iso2: "YE", dial: "967", min: 9, max: 9 },
  { name: "Zambia", iso2: "ZM", dial: "260", min: 9, max: 9 },
  { name: "Zimbabwe", iso2: "ZW", dial: "263", min: 9, max: 9 },
];

const MORE_COUNTRIES: Country[] = [
  { name: "Andorra", iso2: "AD", dial: "376", min: 6, max: 9 },
  { name: "Angola", iso2: "AO", dial: "244", min: 9, max: 9 },
  { name: "Bahamas", iso2: "BS", dial: "1", min: 10, max: 10 },
  { name: "Barbados", iso2: "BB", dial: "1", min: 10, max: 10 },
  { name: "Belize", iso2: "BZ", dial: "501", min: 7, max: 7 },
  { name: "Benin", iso2: "BJ", dial: "229", min: 8, max: 8 },
  { name: "Bhutan", iso2: "BT", dial: "975", min: 8, max: 8 },
  { name: "Botswana", iso2: "BW", dial: "267", min: 7, max: 8 },
  { name: "Brunei", iso2: "BN", dial: "673", min: 7, max: 7 },
  { name: "Burkina Faso", iso2: "BF", dial: "226", min: 8, max: 8 },
  { name: "Burundi", iso2: "BI", dial: "257", min: 8, max: 8 },
  { name: "Congo (DRC)", iso2: "CD", dial: "243", min: 9, max: 9 },
  { name: "Cuba", iso2: "CU", dial: "53", min: 8, max: 8 },
  { name: "Eritrea", iso2: "ER", dial: "291", min: 7, max: 7 },
  { name: "Fiji", iso2: "FJ", dial: "679", min: 7, max: 7 },
  { name: "Gabon", iso2: "GA", dial: "241", min: 7, max: 8 },
  { name: "Guinea", iso2: "GN", dial: "224", min: 9, max: 9 },
  { name: "Guyana", iso2: "GY", dial: "592", min: 7, max: 7 },
  { name: "Haiti", iso2: "HT", dial: "509", min: 8, max: 8 },
  { name: "Iran", iso2: "IR", dial: "98", min: 10, max: 10 },
  { name: "Ivory Coast", iso2: "CI", dial: "225", min: 10, max: 10 },
  { name: "Kosovo", iso2: "XK", dial: "383", min: 8, max: 9 },
  { name: "Laos", iso2: "LA", dial: "856", min: 8, max: 10 },
  { name: "Lesotho", iso2: "LS", dial: "266", min: 8, max: 8 },
  { name: "Liberia", iso2: "LR", dial: "231", min: 7, max: 9 },
  { name: "Liechtenstein", iso2: "LI", dial: "423", min: 7, max: 9 },
  { name: "Macau", iso2: "MO", dial: "853", min: 8, max: 8 },
  { name: "Madagascar", iso2: "MG", dial: "261", min: 9, max: 9 },
  { name: "Malawi", iso2: "MW", dial: "265", min: 7, max: 9 },
  { name: "Mali", iso2: "ML", dial: "223", min: 8, max: 8 },
  { name: "Mauritania", iso2: "MR", dial: "222", min: 8, max: 8 },
  { name: "Monaco", iso2: "MC", dial: "377", min: 8, max: 9 },
  { name: "Mongolia", iso2: "MN", dial: "976", min: 8, max: 8 },
  { name: "Montenegro", iso2: "ME", dial: "382", min: 8, max: 9 },
  { name: "Mozambique", iso2: "MZ", dial: "258", min: 9, max: 9 },
  { name: "Myanmar", iso2: "MM", dial: "95", min: 8, max: 10 },
  { name: "Namibia", iso2: "NA", dial: "264", min: 8, max: 9 },
  { name: "Nicaragua", iso2: "NI", dial: "505", min: 8, max: 8 },
  { name: "Niger", iso2: "NE", dial: "227", min: 8, max: 8 },
  { name: "Palestine", iso2: "PS", dial: "970", min: 9, max: 9 },
  { name: "Papua New Guinea", iso2: "PG", dial: "675", min: 7, max: 8 },
  { name: "Puerto Rico", iso2: "PR", dial: "1", min: 10, max: 10 },
  { name: "Rwanda", iso2: "RW", dial: "250", min: 9, max: 9 },
  { name: "San Marino", iso2: "SM", dial: "378", min: 6, max: 10 },
  { name: "Sierra Leone", iso2: "SL", dial: "232", min: 8, max: 8 },
  { name: "Somalia", iso2: "SO", dial: "252", min: 7, max: 9 },
  { name: "South Sudan", iso2: "SS", dial: "211", min: 9, max: 9 },
  { name: "Sudan", iso2: "SD", dial: "249", min: 9, max: 9 },
  { name: "Suriname", iso2: "SR", dial: "597", min: 6, max: 7 },
  { name: "Syria", iso2: "SY", dial: "963", min: 9, max: 9 },
  { name: "Tajikistan", iso2: "TJ", dial: "992", min: 9, max: 9 },
  { name: "Togo", iso2: "TG", dial: "228", min: 8, max: 8 },
  { name: "Trinidad and Tobago", iso2: "TT", dial: "1", min: 10, max: 10 },
  { name: "Turkmenistan", iso2: "TM", dial: "993", min: 8, max: 8 },
];

export const COUNTRIES: Country[] = [...BASE_COUNTRIES, ...MORE_COUNTRIES].sort((a, b) => a.name.localeCompare(b.name));

/** Flag emoji from an ISO-3166 alpha-2 code (regional indicator letters). */
export function flagEmoji(iso2: string): string {
  if (!/^[A-Za-z]{2}$/.test(iso2)) return "🏳️";
  const base = 0x1f1e6;
  const cp = iso2
    .toUpperCase()
    .split("")
    .map((c) => base + (c.charCodeAt(0) - 65));
  return String.fromCodePoint(...cp);
}

export function countryByName(name: string | null | undefined): Country | undefined {
  if (!name) return undefined;
  const n = name.trim().toLowerCase();
  return COUNTRIES.find((c) => c.name.toLowerCase() === n);
}
