"use client";
import { useEffect,useState } from "react";
import { apiFetch } from "@/lib/api-client";
import { Button } from "@/components/ui/Button";
type Staff={id:string;fullName:string;email:string;role:string;status:string;staffPermissions:{module:string}[]};
const labels:Record<string,string>={overview:"Overview",orders:"Orders",customers:"Customers",applications:"Applications",documents:"Documents",finance:"Finance",packages:"Packages",communications:"Communications",tasks:"Tasks",reports:"Reports","audit-log":"Audit log"};
export function StaffManager(){const [staff,setStaff]=useState<Staff[]>([]);const [modules,setModules]=useState<string[]>([]);const [form,setForm]=useState({fullName:"",email:"",password:"",role:"STAFF",modules:[] as string[]});const [message,setMessage]=useState("");
 const load=()=>apiFetch<{staff:Staff[];modules:string[]}>("/api/admin/staff").then(x=>{setStaff(x.staff);setModules(x.modules)}).catch(e=>setMessage(e.message));useEffect(()=>{load()},[]);
 const toggle=(m:string)=>setForm({...form,modules:form.modules.includes(m)?form.modules.filter(x=>x!==m):[...form.modules,m]});
 async function add(e:React.FormEvent){e.preventDefault();setMessage("");try{await apiFetch("/api/admin/staff",{method:"POST",body:JSON.stringify(form)});setForm({fullName:"",email:"",password:"",role:"STAFF",modules:[]});setMessage("Staff account created.");await load()}catch(x){setMessage(x instanceof Error?x.message:"Account could not be created.")}}
 async function update(s:Staff){await apiFetch(`/api/admin/staff/${s.id}`,{method:"PATCH",body:JSON.stringify({role:s.role,status:s.status,modules:s.staffPermissions.map(p=>p.module)})});setMessage("Staff access updated.");await load()}
 return <div className="grid gap-6 xl:grid-cols-[380px_1fr]"><form onSubmit={add} className="h-fit rounded-2xl border border-border bg-white p-6 shadow-sm"><h2 className="text-lg font-extrabold">Add staff member</h2><div className="mt-5 space-y-3">{[["fullName","Full name"],["email","Email address"],["password","Temporary password"]].map(([k,l])=><label key={k} className="block"><span className="mb-1 block text-sm font-semibold">{l}</span><input required type={k==="password"?"password":k==="email"?"email":"text"} className="h-11 w-full rounded-lg border border-border px-3" value={String(form[k as keyof typeof form])} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<select className="h-11 w-full rounded-lg border border-border px-3" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="STAFF">Staff</option><option value="ADMIN">Administrator</option></select><fieldset><legend className="text-sm font-semibold">Module access</legend><div className="mt-2 grid grid-cols-2 gap-2">{modules.map(m=><label key={m} className="flex gap-2 text-sm"><input type="checkbox" checked={form.modules.includes(m)} onChange={()=>toggle(m)}/>{labels[m]}</label>)}</div></fieldset><Button type="submit" className="w-full">Create staff account</Button></div></form><div className="space-y-4">{staff.map((s,i)=><article key={s.id} className="rounded-2xl border border-border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-extrabold">{s.fullName}</h3><p className="text-sm text-text-mid">{s.email}</p></div>{s.role==="SUPER_ADMIN"?<span className="rounded-full bg-blue/10 px-3 py-1 text-xs font-bold text-blue">Super administrator</span>:<div className="flex gap-2"><select className="rounded-lg border border-border px-2" value={s.role} onChange={e=>setStaff(staff.map((x,j)=>j===i?{...x,role:e.target.value}:x))}><option value="STAFF">Staff</option><option value="ADMIN">Administrator</option></select><select className="rounded-lg border border-border px-2" value={s.status} onChange={e=>setStaff(staff.map((x,j)=>j===i?{...x,status:e.target.value}:x))}><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option></select></div>}</div>{s.role!=="SUPER_ADMIN"&&<><div className="mt-4 grid gap-2 sm:grid-cols-3">{modules.map(m=><label key={m} className="flex gap-2 text-sm"><input type="checkbox" checked={s.staffPermissions.some(p=>p.module===m)} onChange={()=>setStaff(staff.map((x,j)=>j===i?{...x,staffPermissions:x.staffPermissions.some(p=>p.module===m)?x.staffPermissions.filter(p=>p.module!==m):[...x.staffPermissions,{module:m}]}:x))}/>{labels[m]}</label>)}</div><Button className="mt-4" size="sm" onClick={()=>update(s)}>Save access</Button></>}</article>)}</div>{message&&<p className="text-sm font-semibold text-blue xl:col-span-2">{message}</p>}</div>}
